#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sunshine.Tests.Resource", IsApplication=true)]

namespace Sunshine.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Sunshine.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Sunshine.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Sunshine.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Sunshine.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Sunshine.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Sunshine.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Sunshine.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Sunshine.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Sunshine.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Sunshine.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Sunshine.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Sunshine.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Sunshine.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Sunshine.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Sunshine.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Sunshine.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Sunshine.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Sunshine.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Sunshine.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Sunshine.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Sunshine.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Sunshine.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int hockeyapp_background_header = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int hockeyapp_background_light = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int hockeyapp_background_white = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int hockeyapp_button_background = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int hockeyapp_button_background_pressed = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int hockeyapp_button_background_selected = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int hockeyapp_text_black = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int hockeyapp_text_light = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int hockeyapp_text_normal = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int hockeyapp_text_white = 2131165193;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001d
			public const int OptionHostName = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int OptionPort = 2131230750;
			
			// aapt resource value: 0x7f08001c
			public const int OptionRemoteServer = 2131230748;
			
			// aapt resource value: 0x7f08002c
			public const int OptionsButton = 2131230764;
			
			// aapt resource value: 0x7f080027
			public const int ResultFullName = 2131230759;
			
			// aapt resource value: 0x7f080029
			public const int ResultMessage = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int ResultResultState = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int ResultRunSingleMethodTest = 2131230758;
			
			// aapt resource value: 0x7f08002a
			public const int ResultStackTrace = 2131230762;
			
			// aapt resource value: 0x7f080022
			public const int ResultsFailed = 2131230754;
			
			// aapt resource value: 0x7f08001f
			public const int ResultsId = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int ResultsIgnored = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int ResultsInconclusive = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int ResultsMessage = 2131230757;
			
			// aapt resource value: 0x7f080021
			public const int ResultsPassed = 2131230753;
			
			// aapt resource value: 0x7f080020
			public const int ResultsResult = 2131230752;
			
			// aapt resource value: 0x7f08002b
			public const int RunTestsButton = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int TestSuiteListView = 2131230765;
			
			// aapt resource value: 0x7f08000d
			public const int button_add_response = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int button_attachment = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int button_login = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int button_refresh = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int button_send = 2131230729;
			
			// aapt resource value: 0x7f080016
			public const int button_update = 2131230742;
			
			// aapt resource value: 0x7f080004
			public const int input_email = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int input_message = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int input_name = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int input_password = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int input_subject = 2131230725;
			
			// aapt resource value: 0x7f080018
			public const int label_author = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int label_date = 2131230745;
			
			// aapt resource value: 0x7f08000b
			public const int label_last_updated = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int label_message = 2131230720;
			
			// aapt resource value: 0x7f08001a
			public const int label_text = 2131230746;
			
			// aapt resource value: 0x7f080014
			public const int label_title = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int label_version = 2131230741;
			
			// aapt resource value: 0x7f08001b
			public const int list_attachments = 2131230747;
			
			// aapt resource value: 0x7f08000f
			public const int list_feedback_messages = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int text_headline = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int view_header = 2131230739;
			
			// aapt resource value: 0x7f080017
			public const int web_update_details = 2131230743;
			
			// aapt resource value: 0x7f080007
			public const int wrapper_attachments = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int wrapper_feedback = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int wrapper_feedback_scroll = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int wrapper_messages = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int wrapper_messages_buttons = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int hockeyapp_activity_expiry_info = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_activity_feedback = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_activity_login = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_activity_update = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_fragment_update = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_view_feedback_message = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int options = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int results = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int test_result = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int test_suite = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hockeyapp_crash_dialog_message = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hockeyapp_crash_dialog_negative_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hockeyapp_crash_dialog_neutral_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hockeyapp_crash_dialog_positive_button = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hockeyapp_crash_dialog_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hockeyapp_dialog_error_message = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hockeyapp_dialog_error_title = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hockeyapp_dialog_negative_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int hockeyapp_dialog_positive_button = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int hockeyapp_download_failed_dialog_message = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hockeyapp_download_failed_dialog_negative_button = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_download_failed_dialog_positive_button = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_download_failed_dialog_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_error_no_network_message = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_expiry_info_text = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_expiry_info_title = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_feedback_attach_file = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_feedback_attach_picture = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_feedback_attachment_button_text = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int hockeyapp_feedback_attachment_error = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int hockeyapp_feedback_attachment_loading = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int hockeyapp_feedback_email_hint = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int hockeyapp_feedback_failed_text = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int hockeyapp_feedback_failed_title = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int hockeyapp_feedback_generic_error = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int hockeyapp_feedback_last_updated_text = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int hockeyapp_feedback_max_attachments_allowed = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int hockeyapp_feedback_message_hint = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int hockeyapp_feedback_name_hint = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int hockeyapp_feedback_refresh_button_text = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int hockeyapp_feedback_response_button_text = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int hockeyapp_feedback_select_file = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hockeyapp_feedback_select_picture = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int hockeyapp_feedback_send_button_text = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int hockeyapp_feedback_send_generic_error = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int hockeyapp_feedback_send_network_error = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int hockeyapp_feedback_subject_hint = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int hockeyapp_feedback_title = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int hockeyapp_feedback_validate_email_empty = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int hockeyapp_feedback_validate_email_error = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int hockeyapp_feedback_validate_name_error = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int hockeyapp_feedback_validate_subject_error = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int hockeyapp_feedback_validate_text_error = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int hockeyapp_login_email_hint = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int hockeyapp_login_headline_text = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int hockeyapp_login_headline_text_email_only = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int hockeyapp_login_login_button_text = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int hockeyapp_login_missing_credentials_toast = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int hockeyapp_login_password_hint = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int hockeyapp_paint_dialog_message = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int hockeyapp_paint_dialog_negative_button = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int hockeyapp_paint_dialog_neutral_button = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int hockeyapp_paint_dialog_positive_button = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int hockeyapp_paint_indicator_toast = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int hockeyapp_paint_menu_clear = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int hockeyapp_paint_menu_save = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int hockeyapp_paint_menu_undo = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int hockeyapp_permission_dialog_negative_button = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int hockeyapp_permission_dialog_positive_button = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int hockeyapp_permission_update_message = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int hockeyapp_permission_update_title = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int hockeyapp_update_button = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int hockeyapp_update_dialog_message = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int hockeyapp_update_dialog_negative_button = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int hockeyapp_update_dialog_positive_button = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int hockeyapp_update_dialog_title = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int hockeyapp_update_mandatory_toast = 2131034180;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HockeyApp_ButtonStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int HockeyApp_EditTextStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int HockeyApp_SingleLineInputStyle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
